name: "detekt-validation"
on:
  workflow_call:
jobs:
  build:
    name: Build project with gradle
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
    strategy:
      matrix:
        target: [ "convention", "minecraft", "android" ]
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4
      - name: Set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Give gradle permission
        run: chmod +x gradlew