name: "detekt-validation"
on:
  workflow_call:
jobs:
  build:
    name: Build project with gradle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ "convention", "minecraft", "android" ]
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4
      - name: Set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: Publish ${{ matrix.target }}
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :build-logic:plugins:${{ matrix.target }}:publishToMavenLocal --stacktrace
