name: "Test publish"
on:
  workflow_call:
    secrets:
      ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME:
        required: true
      ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD:
        required: true
      ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY:
        required: true
      ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID:
        required: true
      ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD:
        required: true

jobs:
  publish:
    strategy:
      matrix:
        target:
          - ":build-logic:plugins:android:publishAllPublicationsToMavenCentralRepository"
          - ":build-logic:plugins:convention:publishAllPublicationsToMavenCentralRepository"
          - ":build-logic:plugins:minecraft:publishAllPublicationsToMavenCentralRepository"
    name: "Try publish local"
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: Run publish
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ${{ matrix.target }} --stacktrace
  release:
    needs: [ publish ]
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # steps.read_version.outputs.value
      - uses: SebRollen/toml-action@v1.2.0
        id: read_version
        with:
          file: './gradle/libs.versions.toml'
          field: 'project-version-string'
      # steps.read_name.outputs.value
      - uses: SebRollen/toml-action@v1.2.0
        id: read_name
        with:
          file: './gradle/libs.versions.toml'
          field: 'project-name'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          tag_name: ${{ steps.read_version.outputs.value }}
          name: ${{ steps.read_name.outputs.value }} - ${{ steps.read_version.outputs.value }}
          draft: false
          prerelease: false