name: "Test publish"
on:
  workflow_call:
    secrets:
      SIGNING_KEY_ID:
        required: true
      SIGNING_PASSWORD:
        required: true
      OSSRH_USERNAME:
        required: true
      OSSRH_PASSWORD:
        required: true
      SIGNING_KEY:
        required: true

jobs:
  publish:
    strategy:
      matrix:
        target:
          - ":build-logic:plugins:android:publish"
          - ":build-logic:plugins:convention:publish"
          - ":build-logic:plugins:minecraft:publish"
    name: "Try publish local"
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: Run publish
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ${{ matrix.target }} --stacktrace
  release:
    needs: [ publish ]
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # steps.read_version.outputs.value
      - uses: SebRollen/toml-action@v1.2.0
        id: read_version
        with:
          file: './gradle/libs.versions.toml'
          field: 'project-version-string'
      # steps.read_name.outputs.value
      - uses: SebRollen/toml-action@v1.2.0
        id: read_name
        with:
          file: './gradle/libs.versions.toml'
          field: 'project-name'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          tag_name: ${{ steps.read_version.outputs.value }}
          name: ${{ steps.read_name.outputs.value }} - ${{ steps.read_version.outputs.value }}
          draft: false
          prerelease: false