name: Pull request
on:
  pull_request:
    branches:
      - 'develop'
      - 'master'
      - 'prerelease/*'

# Concurrency strategy:
#   github.workflow: distinguish this workflow from others
#   github.event_name: distinguish `push` event from `pull_request` event
#   github.ref_name: distinguish branch
#   github.repository: distinguish owner+repository
#
# Reference:
#   https://docs.github.com/en/actions/using-jobs/using-concurrency
#   https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{github.ref_name}}-${{github.repository}}
  cancel-in-progress: true

jobs:
  gradle_validation:
    name: Validate gradle wrapper
    uses: ./.github/workflows/gradle-wrapper-validation.yml
  detekt_validation:
    name: Check by detekt
    needs: gradle_validation
    uses: ./.github/workflows/detekt-validation.yml
  build:
    name: Build project
    needs: [ gradle_validation, detekt_validation ]
    uses: ./.github/workflows/build-project.yml