name: Publish release

on:
  push:
    branches:
      - master

jobs:
  gradle_validation:
    uses: ./.github/workflows/call-gradle-wrapper-validation.yml
  publish:
    name: Publish library at mavenCentral
    runs-on: macOS-latest
    needs: [ gradle_validation ]
    strategy:
      matrix:
        target: [ "convention", "android", "minecraft" ]
    env:
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: Run publish
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :build-logic:plugins:${{ matrix.target }}:publish --stacktrace
  release:
    needs: [ publish ]
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: christian-draeger/read-properties@1.1.1
        id: properties
        with:
          path: './gradle.properties'
          properties: 'project.name project.version.string'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          tag_name: ${{ steps.properties.outputs.makeevrserg-project-version-string }}
          name: ${{ steps.properties.outputs.makeevrserg-project-name }} - ${{ steps.properties.outputs.makeevrserg-project-version-string }}
          draft: false
          prerelease: false