name: Publish release

on:
  push:
    branches:
      - master

jobs:
  gradle_validation:
    uses: ./.github/workflows/gradle-wrapper-validation.yml

  publish:
    name: Publish library at mavenCentral
    runs-on: ubuntu-latest
    needs: [ gradle_validation ]
    env:
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
    strategy:
      matrix:
        target: [ "convention", "minecraft", "android" ]
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4
      - name: Set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: Publish ${{ matrix.target }}
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :build-logic:plugins:${{ matrix.target }}:publishToMavenLocal --stacktrace

  release:
    needs: [ publish ]
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: christian-draeger/read-properties@1.1.1
        id: properties
        with:
          path: './gradle.properties'
          properties: 'makeevrserg.project.name makeevrserg.project.version.string'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          tag_name: ${{ steps.properties.outputs.makeevrserg-project-version-string }}
          name: ${{ steps.properties.outputs.makeevrserg-project-name }} - ${{ steps.properties.outputs.makeevrserg-project-version-string }}
          draft: false
          prerelease: false